CREATE TABLE [dbo].[UOMs] (
    [UOM_ID]     INT            IDENTITY (1, 1) NOT NULL,
    [UOM_Name]   NVARCHAR (150) CONSTRAINT [DF_UOMs_UOM_Name] DEFAULT ('') NOT NULL,
    [UOM_Code]   NVARCHAR (50)  CONSTRAINT [DF_UOMs_UOM_Code] DEFAULT ('') NOT NULL,
    [UOM_Active] BIT            CONSTRAINT [DF_UOMs_UOM_Active] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_UOMs] PRIMARY KEY CLUSTERED ([UOM_ID] ASC)
);


GO

